### ISSUE TITLE
The type `ImgUtilKey` should be renamed

### ISSUE THREAD

**Issue by kfl** [diku-dk/diku-canvas#12]
The type `ImgUtilKey` should be renamed to `CanvasKey` or something.

Alas, this is a breaking API change.

**Comment by madsobitsoe** [comment]
Could we alias ImgUtilKey and CanvasKey, and add the `[<Deprecated>]` attribute to ImgUtilKey, in order to make the change without breaking the API (at this point in time)?

**Comment by kfl** [comment]
We could. But I prefer to make the name change together with other API changes. I think we want to overhaul the keyboard/event API anyway.

**Comment by madsobitsoe** [comment]
I think that is a brilliant idea. 
At least my contributions are designed by "What can I make work in 5 minutes" and not a good idea.

**Comment by kfl** [comment]
Done in version 2.0
