### ISSUE TITLE
`show` should take title as first argument

### ISSUE THREAD

**Issue by kfl** [diku-dk/diku-canvas#14]
The order of the title and canvas argument for `show` should be the same as for `runApp` and `runSimpleApp`.

**Comment by madsobitsoe** [comment]
I believe Jon specifically requested that Canvas be the first argument to all functions using a Canvas, in order to make currying possible. 

I do not necessarily agree, but it might be worth keeping in my mind before changing.

**Comment by kfl** [comment]
No longer relevant in version 2.0.

There is no longer a `show` function (instead there is a `render` function, that takes title as the first argument)
