### ISSUE TITLE
`scale` is undocumented and may do something wrong

### ISSUE THREAD

**Issue by kfl** [diku-dk/diku-canvas#15]
The following code is expected to show a white canvas:

```fsharp
let bug =
    let canvas = Canvas.create 120 108
    Canvas.runApp "Opps" 120 108
                  (fun w h _ -> Canvas.scale canvas w h) (fun _ _ -> None) ()
```

However some garbled data is shown:

![image](https://user-images.githubusercontent.com/44830/189519893-a7d2ff15-4fe4-4ca8-8f4f-a8c2db5c1c47.png)

May be related to #13

**Comment by joshniemela** [comment]
![image](https://user-images.githubusercontent.com/88747315/199368248-45a74529-6e3c-4b84-96d6-f5edef0b8ce9.png)
I'm unable to reproduce the bug

**Comment by Xatha** [comment]
Hello @kfl! I am also unable to reproduce this bug on Windows 11 (x86-64) and MacOS Apple M1 (ARM) . 
![image](https://user-images.githubusercontent.com/43752641/199368717-135653cc-79dc-4ae0-8722-1ef49f77611a.png)

**Comment by kfl** [comment]
No longer relevant in version 2.0
