### ISSUE TITLE
API for drawing round shapes

### ISSUE THREAD

**Issue by kfl** [diku-dk/diku-canvas#17]
There is no way to draw round/curvy shapes.

For circular shapes:

```fsharp
val strokeArc : canvas -> color -> (x:int, y:int) -> (radius:int) -> (startAngle:int) -> (endAngle:int) -> unit
val fillArc : canvas -> color -> (x:int, y:int) -> (radius:int) -> (startAngle:int) -> (endAngle:int) -> unit
```

For a circular arc with color `color` centered at `(x, y)` with a radius of `radius`. The path starts at `startAngle`, ends at `endAngle`, and travels in clockwise direction, angles are given in radians. Thus, to draw a full blue circle (moon) at position (42, 69) with a radius of 20:

```fsharp
fillArc canvas blue (42,69) 20 0 (2 * int(2.0 * System.Math.PI))
```

Similar for elliptical shapes:

```fsharp
val strokeEllipse : canvas -> color -> (x, y) -> radiusX -> radiusY -> rotation -> startAngle -> endAngle -> unit
val fillEllipse : canvas -> color -> (x, y) -> radiusX -> radiusY -> rotation -> startAngle -> endAngle -> unit
```

For an elliptical arc centred at `(x, y)` with the radii `radiusX` and `radiusY`. Starts at `startAngle` and ends at `endAngle`, and travels in clockwise direction.

**Comment by joshniemela** [comment]
I've made a PR for the first of the four functions.

**Comment by kfl** [comment]
Version 2.0 provide round shapes (amongst other things)
